### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by tonyjemba** [zero-to-mastery/JS_Fun_Practice#146]
Someone to please enlighten me more on how to use the project and contribute to it, thanks.

**Comment by vijay2249** [comment]
Please go through how to contribute repo in the organization about how to contribute and how to use github for open source projects
Also, the conditions and steps may vary from repository to repository, so go through the repository readme file too

**Comment by tonyjemba** [comment]
Okay thanks!

**Comment by vijay2249** [comment]
@tonyjemba if your doubt is cleared, can you close the issue..?

**Comment by tonyjemba** [comment]
oh sure!
