### ISSUE TITLE
Parenthese Mismatch

### ISSUE THREAD

**Issue by musagenius345** [zero-to-mastery/JS_Fun_Practice#243]
The readme contains a potential parentheses mismatch in the `addmTwo` example, specifically in the second usage example:

```javascript
addmTwo(m(1, m(Math.PI, 'pi'))) // {value:4.14159..., source:"(1+pi)"}
```

It seems there might be an extra closing parenthesis at the end of the `source` value. The correct representation should likely be:

```javascript
addmTwo(m(1), m(Math.PI, 'pi')) // {value:4.14159..., source:"(1+pi)"}
```

This adjustment ensures that the parentheses in the `source` value are properly matched and represent the intended mathematical expression.

Please review and address this discrepancy in the readme. 

**Thank you!**

**Comment by Ankush142930** [comment]
Is this issue still open?
