### ISSUE TITLE
[Enhancement]: Add tests

### ISSUE THREAD

**Issue by sophiabrandt** [zero-to-mastery/JS_Fun_Practice#57]
It would be cool if there was a way to run tests.

Example:
I create a new JavaScript file with my solutions in `Solutions/my-solutions.js`.

I run `npm run test`.

The test runner will tell me if I have any errors.

Caveat: I don't want failing tests to be blocking for a PR. ZTM members should be able to add solution files to this repository regardless of failing tests.

**Comment by hazamaswag** [comment]
@sophiabrandt so, I wrote something similar to this while I was testing the functions, using mocha, chai, sinon, and mocha-sinon
if that is what you mean. And I used the npm run test command to test them. 

I'm not sure what the caveat means though.

**Comment by sophiabrandt** [comment]
@hazamaswag the implementation is up to you. Yes, I mean something like `npm run test` and it should show the passing and failing tests.

The caveat means that failing tests should not hinder other people from being able to push to the repository.
A lot of members add the solutions step by step, so they will still have a lot of failing tests. They still should be able to contribute to the repository.

**Comment by hazamaswag** [comment]
Checkout my pull request. I don't exactly know where to show the code except there. 

I think it achieves what you are describing @sophiabrandt

**Comment by hazamaswag** [comment]
@sophiabrandt Thanks for merging it!

It'd be nice if I could get credit for this issue

**Comment by sophiabrandt** [comment]
Sure, why don't you add a notice to the Readme?

**Comment by hazamaswag** [comment]
I guess I meant to be assigned to the issue. But it’s all good
